version: "3.4"

networks:
    birdsitelivenetwork:
        external: false

services:
    server:
        image: ghcr.io/jim60105/birdsitelive:latest
        restart: always
        container_name: birdsitelive
        environment:
            - Instance__Domain=domain.name
            - Instance__AdminEmail=name@domain.ext
            - Db__Type=postgres
            - Db__Host=db
            - Db__Name=birdsitelive
            - Db__User=birdsitelive
            - Db__Password=birdsitelive
            - Twitter__ConsumerKey=twitter.api.key
            - Twitter__ConsumerSecret=twitter.api.key
            ## Enable this if you encounter issues and need to check the debug logs on page
            # - ASPNETCORE_ENVIRONMENT=Development
        networks:
            - birdsitelivenetwork
        ports:
            - "5000:80"
        depends_on:
            - db

    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=birdsitelive
            - POSTGRES_PASSWORD=birdsitelive
            - POSTGRES_DB=birdsitelive
        networks:
            - birdsitelivenetwork
        volumes:
            - ./postgres:/var/lib/postgresql/data
